### ISSUE TITLE
Firstname/Lastname for Vipps Number transactions

### ISSUE THREAD

**Issue by klaaskooistra** [vippsas/vipps-report-api#39]
Based on the docs you state that information is the same compared to Vipps settlement files. However, its unclear based on the docs if firstname & lastname are still provided for Vipps transactions made to vipps numbers. Could you give some guidance on this topic?

**Comment by audunru** [comment]
Pretty sure there isn't any data from Vipps number at all currently. I can only see Vipps Ecommerce sales in the results from /report/v1/ledgertransactions

**Comment by cloveras** [comment]
@audunru is correct. Please see the API specification: https://developer.vippsmobilepay.com/api/report/#/paths/~1report~1v1~1ledgertransactions/get

There are some GDPR considerations, of course - like accepting to be a data processor.

**Comment by cloveras** [comment]
We have clarified this in the API documentation:

>The Report API is primarily for accounting partners who will use the API to integrate with their accounting systems, allowing them to provide the accounting information to their merchants. 

For more details about each payment: Use the payment API, like `GET:/epayment/v1/payments/{reference}/events`: https://developer.vippsmobilepay.com/api/epayment/#tag/QueryPayments/operation/getPaymentEventLog
