### ISSUE TITLE
vipps nummer

### ISSUE THREAD

**Issue by pietdeprez** [vippsas/vipps-report-api#54]
As a user with only Vipps Nummer cant generate API keys, will vipps reporting api be available for Vipps Nummer also?

**Comment by cloveras** [comment]
Not yet, sorry. See https://developer.vippsmobilepay.com/docs/APIs/report-api/vipps-report-api-faq/#how-can-i-get-access-to-the-api

**Comment by cloveras** [comment]
See "Authentication" for the latest on this: https://developer.vippsmobilepay.com/docs/APIs/report-api/api-guide/overview/

Closing this issue.
