### ISSUE TITLE
Report API only API keys

### ISSUE THREAD

**Issue by audunru** [vippsas/vipps-report-api#56]
It would be very nice to be able to generate API keys that can only access the report API once it is finished. The new API is looking great compared to the old FTP access, especially when Vippsnummer transactions become available in the API as well.

Since this new report API has different use cases than the existing APIs, maybe it's time to make it possible to generate different keys and assign scopes to them. It does not feel right to use the same keys for fetching reports and for accepting payments.

**Comment by cloveras** [comment]
Yes, that is the plan. See "Accounting keys": https://developer.vippsmobilepay.com/docs/partner/partner-keys/#types-of-partner-keys
